### ISSUE TITLE
Data storage & manipulation

### ISSUE THREAD

**Issue by xunafay** [tm-pe2/ai-data#5]
- [ ] Figure out how we're going to store a large amount of data
- [ ] How do we deal with the duplicate data when we manipulate the original data set

**Comment by vdbe** [comment]
- Figure out how we're going to store a large amount of data:
     I would suggest [git lfs](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage) with a [third party server](https://docs.github.com/en/enterprise-server@3.2/admin/user-management/managing-repositories-in-your-enterprise/configuring-git-large-file-storage-for-your-enterprise) since it will probably be to large to store for free on github

**Comment by Alfredo-Vargas** [comment]
Emre and Peter from the AD and SSS Team are already setting up the Server for us.

**Comment by Alfredo-Vargas** [comment]
Only Emre, then in any case the Issue is solved.
